version: '3.4'

services:
  grpcui:
    image: grpcui:dev
    container_name: GrpcUI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "GrpcUI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_grpcui$
    volumes:
      - C:\Users\c.thadkapally\source\repos\GrpcUI\GrpcUI:/app
      - C:\Users\c.thadkapally\source\repos\GrpcUI:/src
      - C:\Users\c.thadkapally\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_grpcui$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_grpcui$ \"/app/bin/Debug/net5.0/GrpcUI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true